### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by ItzFel** [AIPTU/PiggyMinions#13]
Disable minions can't spawn in per world

Example Config:
---
economy:
  #You can use an economy provider (EconomyAPI, MultiEconomy or Experience)
  provider: EconomyAPI
  #This is used for the MultiEconomy provider
  multieconomy-currency: ""
levelup-cost: 1000

#What worlds can minions not spawn in?
worlds: ["world", "lobby"]
...

**Comment by AIPTU** [comment]
Thanks for issue, minions now can spawn per-world check it [here](https://github.com/AIPTU/PiggyMinions/commit/4eb6a917b4f474a0570230a0ad8811ebb782ae89)
