### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ElectroGamesYT** [AIPTU/PiggyMinions#23]
---
### Issue description

- Expected result: To get the minion
- Actual result: Got a player head that did not spawn a minion

### Steps to reproduce the issue
1. Execute the command "/give <PlayerName>skull:3 1 {MinionInformation:{MinionType:{ActionType:0,TargetID:56,TargetMeta:0}}}"
2. Place Head

### OS and versions
* PiggyMinions: Latest
* PocketMine-MP: Latest
* PHP: Idk? The correct version
* Server OS: Windows

**Comment by AIPTU** [comment]
Try reproduce without plugin

![Screenshot_2021-07-11-12-45-37-13_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/85402087/125184220-23bb5600-e246-11eb-82dc-c5b715116c4e.jpg)

**Comment by Mcbeany** [comment]
> ### Issue description
> * Expected result: To get the minion
> * Actual result: Got a player head that did not spawn a minion
> 
> ### Steps to reproduce the issue
> 1. Execute the command "/give skull:3 1 {MinionInformation:{MinionType:{ActionType:0,TargetID:56,TargetMeta:0}}}"
> 2. Place Head
> 
> ### OS and versions
> * PiggyMinions: Latest
> * PocketMine-MP: Latest
> * PHP: Idk? The correct version
> * Server OS: Windows

where's player's name?

**Comment by ElectroGamesYT** [comment]
I got it working, the plugin was crashing. I swear I closed this though...
