### ISSUE TITLE
Weird restart issue

### ISSUE THREAD

**Issue by ElectroGamesYT** [AIPTU/PiggyMinions#24]
---
### Issue description

- Expected result: For my minions open upgraded slots to save/work properly after server restart
- Actual result: When the sever was restarted all of my open slots (Except first) was filled with a grey stained glass painting

### Steps to reproduce the issue
1. Upgrade the Minion
2. Restart the server
3. Check the Minion's inventory

### OS and versions
* PiggyMinions: Latest
* PocketMine-MP: Latest
* PHP: The correct version
* Server OS: Windows

![Screenshot (1629)](https://user-images.githubusercontent.com/34932094/125207801-07beb100-e254-11eb-8348-c028de7611d1.png)

**Comment by Mcbeany** [comment]
we will fix it soon

**Comment by Mcbeany** [comment]
fixed
