### ISSUE TITLE
Minion Command

### ISSUE THREAD

**Issue by ElectroGamesYT** [AIPTU/PiggyMinions#29]
You should add `/minion <Player> <Type> <Target> <Meta>` as using /give, a message will pop up in chat saying console or who ever gave the player the minion which looks unprofessional.
Also add a custom name to the minion item/head.

**Comment by llPushkarSinghll** [comment]
👍

**Comment by Mcbeany** [comment]
This feature will be added in version 2.0 with upgrades and stuff

**Comment by llPushkarSinghll** [comment]
Ok thx

**Comment by MrNinja008** [comment]
👍

**Comment by ElectroGamesYT** [comment]
> This feature will be added soon

Any idea when soon is?

**Comment by Mcbeany** [comment]
currently working

**Comment by llPushkarSinghll** [comment]
Ok

**Comment by MrNinja008** [comment]
Mcbeany: currently working (11days ago)

**Comment by MrNinja008** [comment]
@Mcbeany @AIPTU ded

**Comment by VrisQ** [comment]
Legends say that they are still working on the suggestion above 👆

**Comment by Mcbeany** [comment]
haha lol

**Comment by Mcbeany** [comment]
moved to https://github.com/Mcbeany/BetterMinion

**Comment by llPushkarSinghll** [comment]
Bruh lol xD
