### ISSUE TITLE
Skyblock Support

### ISSUE THREAD

**Issue by VrisQ** [AIPTU/PiggyMinions#30]
Add support for andresbytes SkyBlock plugin 

I assume this plugin is mainly gonna be used for skyblock.

 While you can disable a specific world, there are still tons of skyblock worlds where you can place them.

So a feature where you can only place the minion on the island’s you are part of would be really nice.

**Comment by ElectroGamesYT** [comment]
There is really no point of this since you can disable specific worlds as you said.
If you didn't know, you can disable as many worlds as you would like, not just one.
