### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by llPushkarSinghll** [AIPTU/PiggyMinions#31]
Add two more things if u can 🙂

Auto Smelter- Automatically smelts items that the minion produces.

Compactor- 
Compacts items to their block forms.
Example:
9 Iron > Block of Iron
4 Glowstone Dust > Glowstone

**Comment by Mcbeany** [comment]
yeah we are doing it

**Comment by llPushkarSinghll** [comment]
Oh nice

**Comment by llPushkarSinghll** [comment]
> yeah we are doing it

One more suggestions try to add that only specific number of minion can be placed in one world

**Comment by MrNinja008** [comment]
Maybe Fisher Minion? And bone meal Minion like you need to put bone meal in bone meal Minion inv it will spread on farm

**Comment by AIPTU** [comment]
Moved to https://github.com/Mcbeany/BetterMinion
